name: CI to test lint issues
on:
  [push]

jobs:
  lint-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
    - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - uses: actions/checkout@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install -r requirements/ci.txt
    - name: Run pylint commands
      run: |
        pycodestyle .
        pylint tests
